# Build stage
FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Run stage
FROM eclipse-temurin:17-jdk

WORKDIR /app

# Copy target folder
COPY --from=build /app/target /app/target

EXPOSE 8080

# Use CMD instead of ENTRYPOINT
CMD ["sh","-c","java -jar target/*.jar"]
